navikt/syfooversikt

- Mock/Data/aktivenhet.json
- Mock/Data/enheter.json
- Mock/Data/personoversiktEnhet.json
- Mock/mockEndepunkter.js
- src/components/PaginationRow.tsx
- src/components/Sokeresultat.tsx
- src/containers/EnhetensOversiktContainer.tsx
- src/containers/OversiktContainer.tsx
- src/global.ts
- src/index.tsx
- src/store/modiacontext/modiacontextSagas.ts
- src/store/modiacontext/modiacontext_actions.ts
- src/store/personoversikt/personoversiktSagas.ts
- src/store/personoversikt/personoversikt_actions.ts
- src/store/veiledere/veiledereReducer.ts
- src/store/veiledere/veiledereSagas.ts
- src/store/veilederenheter/veilederenheterReducer.ts
- src/store/veilederenheter/veilederenheterTypes.ts
- src/store/veilederenheter/veilederenheter_actions.ts
- src/utils/hendelseFilteringUtils.tsx
- test/components/Sokeresultat.test.tsx
- test/data/fellesTestdata.ts
- test/store/personoversikt/personoversikt_actions.test.ts
- test/store/veilederEnheter/veilederenheterReducer.test.ts
Henter og viser liste over personer fra enhet som er valgt i contextholder(valgt i internarbeidsflatedecorator).
> Use AktivEnhet from syfomodacontextholder

- package-lock.json
- package.json
- server.js
- src/store/personoversikt/personoversiktSagas.ts
- src/store/veilederArbeidstaker/veilederArbeidstakerSagas.ts
- test/store/personoversikt/personoversiktSagas.test.ts
- test/store/veilederArbeidstaker/veilederArbeidstakerSagas.test.ts
This means we avoid the need for CORS in syfooversiktsrv
> Add proxy in node server

- changelogs/2/tour.json
- src/components/HendelseTypeFilter.tsx
- Endre tittel for HendelseTypeFilter IKKE_I_AKTIVITET
- Flytt UFORDELTE_BRUKERE til toppen av HendelseTypeFilter
> Change title of HendelseTypeFilter IKKE_I_AKTIVITET

- src/components/toolbar/Dropdown/Dropdown.tsx
- src/components/toolbar/Dropdown/DropdownButtons.tsx
- src/components/toolbar/SearchVeileder/SearchVeileder.tsx
Filters are now kept active and activated when clicking outside the box.
Text change from Velg to Lagre, and Avbryt to nullstill
> change text and functionality

- src/components/toolbar/AssignVeileder/TildelVeileder.tsx
- src/components/toolbar/Dropdown/Dropdown.tsx
- src/components/toolbar/Dropdown/DropdownButtons.tsx
- src/components/toolbar/SearchVeileder/SearchVeileder.tsx
Dette for å la de komponentene som benytter seg av en dropdown selv bestemme hva 'velg' og 'avbryt' skal hete.
> Add text prop in DropdownButton

- src/components/toolbar/AssignVeileder/TildelVeileder.tsx
- src/components/toolbar/Dropdown/Dropdown.tsx
- src/components/toolbar/Dropdown/DropdownButton.tsx
- src/components/toolbar/Dropdown/DropdownButtons.tsx
- src/components/toolbar/SearchVeileder/SearchVeileder.tsx
Hvis ingen veileder er valgt når knappen trykkes på, vis feilmelding.
Feilmeldingen forsvinner når man velger en veileder, eller dropdownen lukkes.
> Always show Tildel Veileder-button, give error if no veileder is chosen

- Mock/Data/personoversiktEnhet.json
- Mock/mockUtils.js
- src/store/personoversikt/personoversiktSagas.ts
- src/store/personoversikt/personoversiktTypes.ts
- src/store/personregister/personregisterReducer.ts
- test/data/fellesTestdata.ts
- test/store/personregister/personregisterReducer.test.ts
o Syfooversiktsrv returnerer navn for person om det er kommet inn navn og tom streng dersom det ikke er det.
Endrer derfor til følgende:
- Dersom navn ikke er tomt: Sette person sitt navn fra Personoversikt.
- Dersom navn er tomt: Settes person sitt navn til navn som hentes fra Syfoperson
> Map name of person from Personoversikt response

- src/components/Personliste.tsx
Add some colour and change the text for label for ufordelt bruker.
> Label contrast

- src/components/ChevronKnapp.tsx
- src/components/PaginationRow.tsx
- src/components/Sokeresultat.tsx
- src/components/Sorteringsrad.tsx
- src/components/changelog/ChangelogChevronKnapp.tsx
- src/components/changelog/ChangelogModal.tsx
- src/components/changelog/ChangelogWrapper.tsx
- src/components/toolbar/AssignVeileder/TildelVeileder.tsx
- src/components/toolbar/Clickable.tsx
- src/components/toolbar/OpenDropdownButton/OpenDropdownButton.tsx
- src/components/toolbar/PaginationContainer.tsx
- src/components/toolbar/SearchVeileder/SearchVeileder.tsx
- src/components/toolbar/Toolbar.tsx
- src/components/toolbar/ToolbarWrapper.tsx
- src/components/utils/toolbar.ts
- src/styles/themes.js
- src/utils/assignVeilederUtils.tsx
- test/components/Sokeresultat.test.tsx
- test/components/Sorteringsrad.test.tsx
Har manuelt lagt til sticky bar, da den tidligere ble revertet pga knekt søk. Søk er nå fikset.﻿
> Bring the sticky bar back from the dead

- package-lock.json
- package.json
Endte opp med å oppgradere fler en hva tittel på branch tilsier. Testet i preprod. Ser ut som at det fungerer fint! :)
> Upgrade npm packages to mitigate vulnerabilities

- src/components/Personrad.tsx
- src/utils/lenkeUtil.tsx
Link to Oppfolgingsplaner-page if the person has OppfolgingsplanLPSBistandUbehandlet
> Link to Oppfolgingsplan-page in syfomodiaperson

- server.js
Update urls to newest NAIS-ingress and replace service locator with ingress-urls
> Update all urls to external hosts

- .env.template
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- dist/index.html
- server/config.js
- server/proxy.js
Enable fetching of internarbeidsflatedecorator from laptop with naisdevice and use correct version of internarbeidsfaltedecorator in dev-fss.
> Update dev and prod url for internarbeidsflatedecorator

- src/data/personoversiktHooks.ts
- src/index.tsx
- src/utils/timeUtils.ts
Litt hissig bakgrunns-refetch tid, øker med 4x
> Increase staletime for react query

- .github/workflows/redis.yaml
- .nais/redis/redis.yaml
- README.md
Also add github actions workflow for Redis pod deploy
> Add file annotations to Redis NAIS manifest to ensure file system access

- package-lock.json
- package.json
- server.js
Se https://github.com/navikt/syfomodiaperson/pull/499#issue-788763222 for forklaring.
> use helmet

- src/components/NavigationBar.tsx
- src/routers/AppRouter.tsx
- test/containers/OversiktContainer.test.tsx
When no matching route is found, redirect route to route /sykefravaer. This will prevent the user from coming to a blank page, if a wrong url is given as input.
> Add wildcard app route

- server/routes/unleashRoutes.ts
This is needed for toggling aktivitetskrav.
> Add the new unleash strategies

- mock/data/personoversiktEnhet.json
- package-lock.json
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/components/HendelseTypeFilter.tsx
- src/context/filters/filterContextState.ts
- src/data/personoversiktHooks.ts
- src/data/unleash/types/unleash_types.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/lenkeUtil.tsx
- src/utils/personDataUtil.ts
- src/utils/toPersondata.ts
- test/components/HendelseTypeFilter.test.tsx
- test/components/Personrad.test.tsx
- test/components/Sokeresultat.test.tsx
- test/data/fellesTestdata.ts
- test/utils/hendelseFilteringUtilsTest.ts
- test/utils/personDataUtil.test.ts
Add aktivitetskrav fields to DTO.
Add filter for aktivitetskrav.
Label when status is "avvent" will be added later.
> Add aktivitetskrav

- mock/data/personInfo.json
- mock/data/personoversiktEnhet.json
- src/api/types/personregisterTypes.ts
- src/components/Labels.tsx
- src/components/Personrad.tsx
- src/utils/personDataUtil.ts
- test/utils/personDataUtil.test.ts
Replace skjermingskode text with label as well.
> Add label for aktivitetskrav with status "AVVENT"

- mock/data/personoversiktEnhet.json
- package-lock.json
- package.json
- src/components/Labels.tsx
- src/utils/dateUtils.ts
- test/components/Personrad.test.tsx
- test/utils/dateUtils.test.ts
> Viser riktig format på dato i AVVENT label

- package-lock.json
- src/utils/hendelseFilteringUtils.tsx
Previous sorting didn't work, because we used Veileder object, instead of last name as string.
> Sort veiledere by last name

- mock/data/personoversiktEnhet.json
- package-lock.json
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/components/Labels.tsx
- src/utils/toPersondata.ts
- test/components/Personrad.test.tsx
- test/data/fellesTestdata.ts
- test/utils/hendelseFilteringUtilsTest.ts
This requires change in syfooversiktsrv as well.
> Use sistVurdert in aktivitetskrav instead of updatedAt

- .env.template
- src/data/personoversiktHooks.ts
If the only exisiting event on arbeidstaker is aktivitetskrav AND aktivitetskrav is toggled on, include the arbeidstaker in the oversikt.
> Show aktivitetskrav entries if it's toggled on in unleash

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Ref https://trello.com/c/FkW6EYQZ/1232-endringer-i-default-brukertilganger-for-azure-ad-apper
> allowAllUsers: true

- src/components/Personrad.tsx
- src/utils/lenkeUtil.tsx
Dette ser ut til å fungere. Det er mest en quick fix, jeg tror vi på sikt burde se mer på dette, siden koden er litt rar 🤷
> Only send user to syfomodiaperson after successful mutation

- .eslintrc.js
- package-lock.json
- package.json
https://www.npmjs.com/package/eslint-plugin-no-only-tests
> Add eslint plugin no-only-tests

- package-lock.json
- src/components/HendelseTypeFilter.tsx
- src/context/filters/filterContextState.ts
- src/data/unleash/types/unleash_types.ts
- test/components/HendelseTypeFilter.test.tsx
- test/components/Sokeresultat.test.tsx
> Add filter for behandlerdialogoppgave, with toggle

- .husky/pre-commit
- package.json
"It works on my machine"
Slet litt med at plutselig klagde husky og pre-commit. Kan dere sjekke om dette funker hos dere også?
> Fix pre-commit husky script

- mock/data/personoversiktEnhet.json
- mock/mockUtils.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/data/personoversiktHooks.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/toPersondata.ts
- test/components/Personrad.test.tsx
- test/data/fellesTestdata.ts
- test/utils/hendelseFilteringUtilsTest.ts
Avventer til backend er klart! https://github.com/navikt/syfooversiktsrv/pull/282
> Add flag for ubehandlet behandlerdialog used in filter

- .env.template
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- mock/ereg/mockEreg.ts
- mock/mockEndepunkter.ts
- package-lock.json
- server/config.ts
- server/proxy.ts
- src/components/PersonRadVirksomhetColumn.tsx
- src/data/virksomhet/EregVirksomhetsnavn.ts
- src/data/virksomhet/virksomhetQueryHooks.ts
- src/utils/apiUrlUtil.ts
- src/utils/personDataUtil.ts
When this is merged we can remove names from personData.
> Get virksomhetsnavn on demand from ereg

- Dockerfile
Ser det blir en del støy i loggene etter overgangen tlil distroless. Usikker på om dette er noe brukerne merker noe til.
> Bugfix changelog

- src/components/HendelseTypeFilter.tsx
- src/context/tab/TabTypeContext.tsx
- test/components/HendelseTypeFilter.test.tsx
Refaktorert HendelseTypeFilter slik at logikken for å skjule/vise filter-checkbox blir noe enklere. Lagt på typer og bruker disse i case/switch i funksjoner slik at det blir enklere å vite hva som må implementeres når man legger til et nytt filter.
> Refactor show checkbox logic and improved hendelse filter types

- src/data/personoversiktHooks.ts
Lagt til sjekk på huskelappActive i isUbehandlet slik at personer med bare huskelapp og ingen annen ubehandlet oppgave også dukker opp i oversikten.
> IS-1670: Check huskelappActive in isUbehandlet

- mock/data/personoversiktEnhetMock.ts
- server/unleash.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/components/HendelseTypeFilter.tsx
- src/context/filters/filterContextState.ts
- src/data/personoversiktHooks.ts
- src/data/unleash/types/unleash_types.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/lenkeUtil.tsx
- src/utils/toPersondata.ts
- test/components/Personrad.test.tsx
- test/components/Sokeresultat.test.tsx
- test/data/fellesTestdata.ts
- test/query/personoversiktHooks.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
🧑‍💻 Hackathon 🧑‍💻 Lagt til nytt filter for behandler ber om bistand
> Hackathon: Add new filter for behandler ber om bistand

- src/components/HendelseTypeFilter.tsx
- test/components/HendelseTypeFilter.test.tsx
Endret navn på tre hendelser:
Ønsker møte -> Ber om dialogmøte
Arbeidsgiver ønsker bistand -> Arbeidsgiver ber om bistand
Huskelapp -> Trenger oppfølging
> Change HendelseTekster

- server/unleash.ts
- src/components/HendelseTypeFilter.tsx
- src/data/unleash/types/unleash_types.ts
Fjerner toggle som er skrudd på for alle i prod
> IS-1753: Remove toggle enabled in prod

- server/unleash.ts
- src/components/HendelseTypeFilter.tsx
- src/data/unleash/types/unleash_types.ts
- test/components/HendelseTypeFilter.test.tsx
- Slettet kode som henger sammen med `isSendingAvForhandsvarselEnabled`.
> IS-1798: Deleted code associated with toggle

- server/unleash.ts
- src/data/unleash/types/unleash_types.ts
- Slettet kode som henger sammen med toggle `isMotebehovTilbakemeldingEnabled`
> IS-1807: Delete isMotebehovTilbakemeldingEnabled toggle code

- package-lock.json
- package.json
- src/styles/styles.less
Oppgradert Aksel-pakker til v5.x. Vi bruker mest gamle designsystemet her så lite som brekker :see_no_evil:
> IS-1855: Upgrade aksel

- mock/data/personoversiktEnhetMock.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/data/personoversiktHooks.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/toPersondata.ts
- test/components/Personrad.test.tsx
- test/data/fellesTestdata.ts
- test/query/personoversiktHooks.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
- Fikk beskjed fra pilotbrukere om at alle oppgavene om trenger oppfølging er borte. Viste seg at frontend som mottar `PersonOversiktStatusDTO` ([PR](https://github.com/navikt/syfooversiktsrv/pull/339/files#diff-de82ebdb55c4bbec5fb99cafcb6d1775f4f164d27d4e696ab561293f2f9587ea))
> IS-1863: Renamed to be able to receive data correctly from backend

- mock/data/personoversiktEnhetMock.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/utils/toPersondata.ts
- test/components/Personrad.test.tsx
- test/data/fellesTestdata.ts
- test/utils/hendelseFilteringUtilsTest.ts
Lagt til nytt `trengerOppfolgingFrist`-felt fra `syfooversiktsrv` i dtoene - foreløpig ingen visning
> IS-1710: Add trengerOppfolgingFrist to dtos

- src/utils/hendelseFilteringUtils.tsx
- test/utils/hendelseFilteringUtilsTest.ts
Fikset sorteringen slik at tidligste dato kommer først når man sorterer ascending. Tror det skal bli riktigere og på linje med [Aksel](https://aksel.nav.no/komponenter/core/table#tabledemo-sortable)-eksempelet
> IS-1710: Fix sorting bug

- src/utils/hendelseFilteringUtils.tsx
- test/utils/hendelseFilteringUtilsTest.ts
Fikset sortering på sykefravær-varighet-kolonnen til å bruke varighetUker. Sorterer på tilfelle-start-dato som før hvis likt antall uker.
> Sort by varighet then startdate

- package-lock.json
- package.json
- src/api/axios.ts
- test/stubs/stubAktivVeileder.ts
- test/stubs/stubChangelogs.ts
- test/stubs/stubModiaContext.ts
- test/stubs/stubPersonoversikt.ts
- test/stubs/stubPersonregister.ts
- test/stubs/stubVeiledere.ts
Hva er nytt / hva har blitt fikset?
Hvis ny synlig feature – ta screenshot!
> Upgrade axios

- package-lock.json
- package.json
- postcss.config.js
- src/components/HendelseTypeFilter.tsx
- src/components/filters/TekstFilter.tsx
- src/index.tsx
- src/styles/style.css
- tailwind.config.js
- webpack.common.ts
Lagt til tailwind-config og tatt i bruk et par steder. Dette for å enklere kunne kopiere flexjar-komponenter fra syfomodiaperson.
> Add tailwind

- src/components/PersonFilter.tsx
- src/components/filters/FristFilter.tsx
- Setter filter verdier når man rendrer `Checkbox` komponent.
> IS-1964: Add setting of values on render

- src/api/types/personregisterTypes.ts
- src/components/FristColumn.tsx
- src/components/HendelseTypeFilter.tsx
- src/context/filters/filterContextState.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/personDataUtil.ts
- src/utils/toPersondata.ts
- test/components/FristColumnTest.tsx
- test/components/HendelseTypeFilter.test.tsx
- test/components/Personrad.test.tsx
- test/components/Sokeresultat.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
- Navn endring fra "Vurdert for oppfølging" og "Trenger oppfølging" til "Oppfølgingsoppgave.
> IS-1956: Rename from trengeroppfolging to oppfolgingsoppgave

- src/utils/hendelseFilteringUtils.tsx
- Legger til måneder på sortering for fødselsnummer
> IS-2056: Add months for sorting on fnr

- server/unleash.ts
- src/components/HendelseTypeFilter.tsx
- src/data/unleash/types/unleash_types.ts
- test/components/HendelseTypeFilter.test.tsx
- Fjerner toggle for huskelapp
> IS-2063: Remove huskelapp unleash toggle

- src/components/Filter/PersonFilter.tsx
- src/components/Sokeresultat.tsx
- src/components/filters/AgeFilter.tsx
- src/containers/Oversikt.tsx
- src/context/filters/filterContextActions.ts
- src/context/filters/filterContextReducer.ts
- src/context/filters/filterContextState.ts
- src/utils/hendelseFilteringUtils.tsx
- test/components/Sokeresultat.test.tsx
- test/components/filteringUtils.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
- Legger til filter for alder i oversikten
https://github.com/navikt/syfooversikt/assets/11747383/3a3371ed-83c8-404c-a83f-32ae0500f143
> IS-2027: Add age filter

- test/utils/hendelseFilteringUtilsTest.ts
> IS-2027: Remove console.log

- package-lock.json
- package.json
- src/components/EmptyDrawer/EmptyDrawer.tsx
- src/components/MoteoversiktLink.tsx
- src/components/filters/TekstFilter.tsx
Migrert noen lavthengende frukter til Aksel
> Litt Aksel-migrering

- mock/data/personoversiktEnhetMock.ts
- server/unleash.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/components/HendelseTypeFilter.tsx
- src/context/filters/filterContextState.ts
- src/data/personoversiktHooks.ts
- src/data/unleash/types/unleash_types.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/toPersondata.ts
- test/components/FristColumnTest.tsx
- test/components/HendelseTypeFilter.test.tsx
- test/components/Personrad.test.tsx
- test/components/Sokeresultat.test.tsx
- test/data/fellesTestdata.ts
- test/query/personoversiktHooks.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
> IS-2275: Friskmelding til arbeidsformidling

- public/index.html
Se https://nav-it.slack.com/archives/CLJJKQEHY/p1714718167567719?thread_ts=1713181796.482639&cid=CLJJKQEHY.
Urlen vi brukte fungerer ikke lenger - endrer til å bruke ingress
> Fix local decorator url

- package-lock.json
- package.json
- server/unleash.ts
- src/components/flexjar/Flexjar.tsx
- src/containers/OversiktContainer.tsx
- src/data/unleash/types/unleash_types.ts
- src/hooks/useLocalStorageState.ts
- src/utils/amplitude.ts
- src/utils/dateUtils.ts
- test/components/flexjar/FlexjarTest.tsx
- test/containers/OversiktContainer.test.tsx
- test/setup.tsx
- test/stubs/stubFlexjar.ts
- test/testQueryClient.ts
Endringer:
- Flexjar-panel som vises dersom du ikke har svart siste 3 ukene
- Endret marginer på oversikten
- Test-oppsett likt som `syfomodiaperson`
- Toggle der planen er å bruke gradual rollout
<details>
<summary>Screenshots</summary>
</details>
> IS-2379: Add flexjar with Arena-sporsmal

- server/unleash.ts
- src/components/NewOversikt.tsx
- src/components/NewOversiktTable.tsx
- src/components/PersonRadVirksomhetColumn.tsx
- src/components/Personliste.tsx
- src/components/Sokeresultat.tsx
- src/components/Sorteringsrad.tsx
- src/components/toolbar/Toolbar.tsx
- src/components/toolbar/ToolbarWrapper.tsx
- src/data/unleash/types/unleash_types.ts
- src/hooks/useSorting.ts
- src/utils/hendelseFilteringUtils.tsx
- test/components/Sorteringsrad.test.tsx
Mulig det er lurt å legge inn en featuretoggle som en switch ganske høyt oppe i component-treet her, og så bygge litt og litt.
> IS-2440: Add aksel table

- mock/data/personoversiktEnhetMock.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/components/FristColumn.tsx
- src/containers/Oversikt.tsx
- src/data/personoversiktHooks.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/personDataUtil.ts
- src/utils/toPersondata.ts
- test/components/FristColumnTest.tsx
- test/components/NewOversiktTableTest.tsx
- test/data/fellesTestdata.ts
- test/query/personoversiktHooks.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
Foreløpig som tooltip, vi får diskutere mer neste uke.
Har også endret sånn at man ikke bryr seg om `trengerOppfolging` og `trengerOppfolgingFrist` i DTOen, da kan vi fjerne dette fra APIet i `syfooversiktsrv` også 👍🏼
> IS-1932: Show oppfolgingsgrunn as tooltip

- mock/data/personoversiktEnhetMock.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/utils/toPersondata.ts
- test/components/FristColumnTest.tsx
- test/components/NewOversiktTableTest.tsx
- test/data/fellesTestdata.ts
- test/utils/hendelseFilteringUtilsTest.ts
Fjerner felt i dtoen som ikke lenger er i bruk. Kommer ny PR på å fjerne fra backend også.
> IS-2329: Remove unused field

- .env.template
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- Bruk gcp for å nå modiacontextholder
> IS-2494: Use gcp version of modiacontextholder

- src/components/LinkSyfomodiaperson.tsx
- src/components/MoteoversiktLink.tsx
- src/decorator/Decorator.tsx
- src/faro.ts
- src/utils/miljoUtil.ts
- Lager funksjon for å få link til `syfomodiaperson` og `syfomoteoversikt`
> IS-2505-2: Add function for getting correct link to subdomain

- src/components/HendelseTypeFilter.tsx
- Endrer tekst på filter for 8-5
> IS-2585: Change text on filter

- server/unleash.ts
- src/components/NewOversiktTable.tsx
- src/data/unleash/types/unleash_types.ts
- src/hooks/useSorting.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/statusColumnUtils.ts
- test/components/NewOversiktTableTest.tsx
Vi har lagt til en ny kolonne kalt `status`. Vi har bare prøvd oss frem med ordlyden og plassering av kolonnen her så gjerne kom med innspill!
> IS-2475: add status column

- src/components/HendelseTypeFilter.tsx
- src/context/filters/filterContextState.ts
- src/utils/hendelseFilteringUtils.tsx
- test/components/HendelseTypeFilter.test.tsx
- test/components/Sokeresultat.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
- Legger tilbake filter for utgåtte forhåndsvarsler for aktivitetskrav
> IS-2600: Add filter vurder stans in oversikt

- mock/data/personoversiktEnhetMock.ts
- server/unleash.ts
- src/api/types/manglendeMedvirkningDTO.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/components/HendelseTypeFilter.tsx
- src/components/LinkSyfomodiaperson.tsx
- src/context/filters/filterContextState.ts
- src/data/personoversiktHooks.ts
- src/data/unleash/types/unleash_types.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/statusColumnUtils.ts
- src/utils/toPersondata.ts
- test/components/FristColumnTest.tsx
- test/components/HendelseTypeFilter.test.tsx
- test/components/NewOversiktTableTest.tsx
- test/components/Sokeresultat.test.tsx
- test/query/personoversiktHooks.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
Ny hendelse for Manglende medvirkning i oversikten (vises basert på feature toggle)
> IS-2634: Add manglende medvirkning

- src/utils/statusColumnUtils.ts
Retter status-kolonne-logikk slik at frist står som utløpt f.om. dagen etter fristen.
> IS-2657: Fix frist logic

- .env.template
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- public/index.html
- server/config.ts
- server/proxy.ts
- src/decorator/Decorator.tsx
- src/decorator/decoratorConfig.ts
- src/decorator/decoratorProps.ts
- src/utils/miljoUtil.ts
Oppgraderer dekoratøren til V3
> IS-2300: Decorator v3

- server/unleash.ts
- src/components/NewOversiktTable.tsx
- src/data/unleash/types/unleash_types.ts
- Fjerner toggle for å vise/skjule ny kolonne i oversikten
> IS-2729: Remove toggle for hendelse column

- server/unleash.ts
- src/components/HendelseFilterPanel.tsx
- src/data/unleash/types/unleash_types.ts
- Fjerner toggle for manglende medvirkning funksjonalitet
> IS-2729: Remove toggle for manglende medvirkning

- src/components/HendelseFilterPanel.tsx
- src/components/NewOversiktTable.tsx
- src/utils/amplitude.ts
- Måler at man filtrerer på en hendelse
- Måler at man sorterer hendelsene i kolonnen
> IS-2686: add amplitude logging hendelsesfilteret

- src/components/flexjar/Flexjar.tsx
- Fjernet alternativer fra flexjar som er enten ferdig migrert fra arena eller for små
- Splittet opp “Flytte mellom enheter“
- Endret ordlyden til alternativet om 39 ukersoppgaven
> IS-2784: edit choices from flexjar

- src/components/LinkSyfomodiaperson.tsx
- src/utils/amplitude.ts
Måle åpning av enkeltperson i oversikten.
> IS-2792: measure enkeltperson click

- package-lock.json
- package.json
- src/components/NavigationBar.tsx
- src/components/sokperson/SokContainer.tsx
- src/components/sokperson/SokPerson.tsx
- src/components/sokperson/SokPersonResultat.tsx
- src/components/toolbar/ToolbarWrapper.tsx
- src/routers/AppRouter.tsx
- test/components/SokPersonTest.tsx
> IS-2842: Move søk to side og ta i bruk aksel tabs

- src/containers/OversiktContainer.tsx
Forlenget intervallet mellom noen svarer på flexjar og får opp spørring igjen fra 3 til 8 uker.
> IS-2835: extend interval flexjar

- src/components/sokperson/SokPerson.tsx
- src/mocks/data/personoversiktEnhetMock.ts
- test/components/SokPersonTest.tsx
- Gjør det mulig å bare kunne søke på fødselsdato
Se [tilhørende PR i syfooversiktsrv](https://github.com/navikt/syfooversiktsrv/pull/486)
> IS-2853: Enable search only on fodselsdato

- src/sider/sokperson/SokPerson.tsx
Måle hvor mange som prøver å søke på bare fødselsdato eller bare initialer.
> IS-2854: måle hvilke søkefelt som blir brukt

- src/context/filters/FilterContext.tsx
- src/context/filters/filterContextActions.ts
- src/context/filters/filterContextReducer.ts
- src/context/filters/filterContextState.ts
- src/sider/oversikt/Oversikt.tsx
- src/sider/oversikt/filter/HendelseFilter.tsx
- src/sider/oversikt/filter/UfordelteBrukereFilter.tsx
- src/sider/oversikt/sokeresultat/Sokeresultat.tsx
- src/utils/hendelseFilteringUtils.tsx
- test/components/HendelseTypeFilter.test.tsx
- test/components/Sokeresultat.test.tsx
- test/containers/OversiktContainer.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
- Flytter "Ufordelte brukere" filter ut av hendelse filter sjekkboks gruppen
Før
Etter
https://github.com/user-attachments/assets/856cc13f-7576-4a54-a840-818f1a7d31f3
> IS-2914: Place ufordelte brukere filter outside hendelse filter group

- src/utils/hendelseFilteringUtils.tsx
- Fikser dialogmotebehov filter
- Se relatert PR der filterne ikke ble helt riktig endret: https://github.com/navikt/syfooversikt/pull/563
Kan følge opp med en PR der vi skriver tester for disse filterne etter denne er merget
> IS: Fix dialogmotebehov filter

- server/unleash.ts
- src/components/NavigationBar.tsx
- src/data/unleash/types/unleash_types.ts
Fjernet bruk av toggle for søk etter sykmeldt slik at elementet ikke flimrer ved innlasting
> IS-2986: Fjernet bruk av toggle for søk etter sykmeldt slik at elementet ikke flimrer ved innlasting

- src/sider/oversikt/filter/CompanyFilter.tsx
- Alfabetisk rekkefølge i velg virksomhet filteret
Nå: 
Før:
> IS-3052: Sort velg virksomhet

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- README.md
- server/config.ts
- server/session.ts
> IS-3066: Bytter til Valkey

- package-lock.json
- package.json
Glemte å rette versjon som en del av forrige PR: https://github.com/navikt/syfooversikt/pull/604
> IS-3097: Bruker spesifikk versjon av ds-tailwind

- src/components/Side.tsx
- fjernet horisontal scroll bug
> IS-3128: remove horizontal scroll

- server/unleash.ts
- src/data/unleash/types/unleash_types.ts
- Legger til feature toggle for å styre tilgang til tildeling av oppfølgingsenhet -funksjonalitet
> IS-3146: Add feature toggle for tildeling functionality

- src/sider/oversikt/sokeresultat/toolbar/TildelOppfolgingsenhet/TildelOppfolgingsenhetModal.tsx
- Fikser problem når man prøver å tildele flere, men bare får tildelt én person
Problemet👇
https://github.com/user-attachments/assets/d9339e2d-78c9-486f-b7ee-37b2093e8a84
> IS: Fix success message for tildeling one person

- src/mocks/mockSyfobehandlendeenhet.ts
- src/sider/oversikt/sokeresultat/toolbar/TildelOppfolgingsenhet/TildelOppfolgingsenhetModal.tsx
- test/components/TildelOppfolgingsenhetTest.tsx
- test/stubs/stubTildelOppfolgingsenhet.ts
Legger til info om brukerne som flyttes til andre enheter enn Nav Utland
> IS-3260: Show info about persons that is tildelt to enhet

- src/sider/oversikt/filter/VeilederFilter.tsx
Tar i bruk den globale filterstaten for å sette dette som default.
https://github.com/user-attachments/assets/10f3edfb-45db-411d-80c9-18fbf1fc54c4
> IS-3225: Include stored filterstate as default options

- src/sider/oversikt/sokeresultat/oversikttable/EmptyDrawer.tsx
- Sentrerer melding om at det ikke finnes noen i søkeresultatet.
Før
Etter
> IS-3376: Center no people message

- server.ts
Se jira-sak: https://jira.adeo.no/browse/FAGSYSTEM-391602
Fant også at vi blokket noe mot amplitude.
> IS-3385: Allow websocket connection in CSP

- src/components/flexjar/ArenaFlexjar.tsx
- src/components/flexjar/RutingFlexjar.tsx
- src/hooks/useLocalStorageState.ts
- src/sider/oversikt/OversiktContainer.tsx
- test/components/flexjar/ArenaFlexjarTest.tsx
- test/components/flexjar/RutingFlexjarTest.tsx
Dupliserte Arena-spørringen i tilfelle vi vil ha den liggende for å slå på senere. Endret på ting slik at det passer med behovet her. Vi kan helt sikkert lage en mer generell flexjar-løsning som gjenbruker ting, men jeg løste det på denne måten nå.
> IS-3346: Add flexjar for ruting

- public/index.html
- Legger til umami tracking for dev
- Lurer på om alt formateringen er konfigurert i prosjektet. Si ifra hvis ikke så skal jeg få fikset det i editoren min 🙏
> IS-3161: Add umami for dev

- server/unleash.ts
- src/data/unleash/types/unleash_types.ts
- Legg til unleash toggle for kartleggingssporsmål
> IS-3410: Add unleash toggle for kartleggingssporsmal

- src/index.tsx
- Laster inn umami scriptet dynamisk
Testet i dev og ser ut til å fungere
> IS-3377: Fix umami

- src/components/flexjar/RutingFlexjar.tsx
- test/components/flexjar/RutingFlexjarTest.tsx
Endret flexjar ifm. spørsmål om ruting til å ha checkboxes og mulighet for å legge til utdypende informasjon
> IS-3406: Endret flexjar ifm. spørsmål om ruting til å ha checkboxes og mulighet for å legge til utdypende informasjon

- src/api/types/personoversiktTypes.ts
- src/data/personoversiktHooks.ts
- src/mocks/data/personoversiktEnhetMock.ts
- Skjønte ikke helt poenget med `PersonOversiktUbehandletStatusDTO`. Det var vel subsettet av properties i `PersonOversiktStatusDTO` som kan fortelle om en person er ubehandlet eller ikke? 
- Uansett syntes jeg dette var litt ryddigere. Har også lagt inn `isUbehandlet` som en egen funksjon ved siden av `interface`. Det niceste med denne endringen er kanskje at man slipper å gjøre om fra det ene interfacet til det andre i `filteredPersonOversiktStatusList`.
Helt greit å ikke synes at dette var ryddigere. Da bare lar vi være å legge til 😊
> IS: Refactor PersonOversiktStatus interface
