- src/components/toolbar/Dropdown/DropdownButton.tsx
- src/components/toolbar/Dropdown/DropdownButtons.tsx
- src/components/toolbar/SearchVeileder/SearchVeileder.tsx
Fjern diven rundt knappene i dropdown, slik at avbryt-/nullstillknappene legger seg nærmere tildel-/lagreknappene.
Ikke sett showList i SearchVeileder til false når man nullstiller veiledersøket.
> Don't close search veileder dropdown on nullstill, move buttons

- src/store/personInfo/personInfoTypes.ts
- src/store/personregister/personregisterReducer.ts
- test/data/fellesTestdata.ts
- test/store/personNavn/personInfoReducer.test.ts
- test/store/personNavn/personInfoSagas.test.ts
- test/store/personNavn/personInfo_actions.test.ts
- test/store/personregister/personregisterReducer.test.ts
Name is now supplied for all persons from PersonOversikt and hence is not needed from PersonInfo
> Remove name from call PersonInfo

- Mock/Data/personoversiktEnhet.json
- Mock/mockUtils.js
- src/components/HendelseTypeFilter.tsx
- src/store/filters/filterReducer.ts
- src/store/personoversikt/personoversiktTypes.ts
- src/store/personregister/personregisterReducer.ts
- src/store/personregister/personregisterTypes.ts
- src/toggle.ts
- src/utils/hendelseFilteringUtils.tsx
- test/components/HendelseTypeFilter.test.tsx
Show hendelseTypeFilter and number of persons with harOppfolgingsplanLPSBistandUbehandlet. This functionality is toggled on locally and i dev-fss, but is toggle off in prod-fss. The should be toggled on when the sending of Oppfolgingsplaner from LPS is turned on and events are generated by Ispersonoppgave.:
> Add HendelseTypeFilter ARBEIDSGIVER_BISTAND

- server/auth/utils.js
Do not reuse token if it expires in less than 10 seconds. This improvement should avoid token expiration in consuming services.
> Improve expiration check of OBO-token

- changelogs/1/tour.json
- changelogs/2/tour.json
- changelogs/3/tour.json
- changelogs/4/tour.json
- src/components/changelog/ChangelogWrapper.tsx
Rydda litt opp i datoene til changelog filene, da de ikke var på et særlig håndterlig format. Benytter nå ISO-standard: yyyy-mm-dd
> check for old news before displaying changelog

- src/context/notification/NotificationContext.tsx
- test/components/Sokeresultat.test.tsx
Når kall til endepunkt feiler blir `displayNotification` kjørt. Denne oppdaterte alltid `notifications` i `NotificationContext`, som igjen førte til at barn av context (f.eks. Oversikt) alltid ble re-rendret og kall til endepunkt ble kjørt på nytt. Dette førte til at kall som feilet ble kjørt på nytt i evig loop.
> Unngår oppdatering av notifications i context hvis notification finnes fra før

- mock/data/personoversiktEnhet.json
- mock/mockEndepunkter.ts
- mock/mockUtils.js
- mock/unleash/unleashMock.ts
- server.js
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/data/personoversiktHooks.ts
- src/utils/toPersondata.ts
- test/data/fellesTestdata.ts
- test/utils/hendelseFilteringUtilsTest.ts
If Dialogmotekandidat is toggled on, then show person that are Dialogmotekandidat and Dialogmote is not started. A Dialogmote is not started if Motestatus is  null or AVLYST.
> Filter list of Persons based on status of Dialogmote and Kandidat

- mock/data/personoversiktEnhet.json
- package-lock.json
- src/components/Personrad.tsx
- src/components/Sorteringsrad.tsx
- src/components/toolbar/Toolbar.tsx
- src/utils/dateUtils.ts
- src/utils/hendelseFilteringUtils.tsx
- test/utils/dateUtils.test.ts
Kolonnen viser antall uker siden sykemeldingen oppsto, og skal hjelpe veiledere med å kunne prioritere sakene sine enklere på tvers av filtergrupperinger.
`undefined`-verdier rangeres "lavere" enn 0, fordi man helst vil se på de som er høyest antall uker siden, og da vil man ikke at "Ukjent" skal dukke opp der (hvis ukjent i det hele tatt er en greie i prod).
> Add uke column with sorting

- server/routes/unleashRoutes.ts
Forgot this last commit.
This is needed for aktivitetskrav.
We can probably remove the existing "byEnvironment" and remove dialogmotesvar toggle.
> Add ByEnvironmentToggle as unleash strategy

- src/components/NavigationBar.tsx
- src/components/Sokeresultat.tsx
- src/context/filters/FilterContext.tsx
Dette vil ta vare på siste filter f.eks. når man går mellom enhetens oversikt og sykmeldt enkeltperson. ~~Filter nullstilles når man bytter mellom Min oversikt og Enhetens oversikt, så det må vi eventuelt løse ved å lagre siste filter per oversikt på et vis.~~
Endret også slik at vi ikke nullstiller filter når man bytter mellom Min oversikt og Enhetens oversikt, dvs at vi lagrer siste filter på tvers av oversiktene.
OBS: Dersom veileder filtrerer på fødselsnummer vil sessionStorage i nettleseren inneholde hele/deler av fødselsnummer i json-strukturen, men tenker kanskje det er greit siden dette er i en intern app og sessionStorage slettes når fanen lukkes.
> Lagre siste filter i sessionStorage

- src/utils/hendelseFilteringUtils.tsx
- test/utils/hendelseFilteringUtilsTest.ts
Jeg er usikker på hvor lett det er å skjønne hvorfor filteret ser ut som det gjør 🤔 I forrige utgave av koden kunne man returnere true med én gang man fikk match på filter/personData, eller default true hvis ingen ifer slo til (ingen filter var huket av). Det kan man ikke nå, siden man alltid må sjekke alle filtrene.
Tanken er at hvis et filter ikke er huket av, skal det ikke fjerne noe fra listen (return true som default), men hvis filteret er huket av må vi også sjekke om tilhørende verdi i personData er true (eller false for tildeltVeileder).
Første utkast var på formen `!filter.verdi || (filter.verdi && personData.verdi))`. Men hvis `!filter.verdi` ikke slår til, må den jo være true, så da kan vi droppe den sjekken etter `||`.
> Use intersection instead of union when filtering

- src/utils/lenkeUtil.tsx
Vi hadde ingen direkte lenking til dialogmeldinger.
Den defaultet bare til personen, slik som for `Positiv Natthegre`
For `Smekker Gapahuk`, som har flere oppgaver, blir det fortsatt slik, selv om filteret for meldinger er valgt. Kanskje en veileder-win å fikse på sikt?
> Use correct link when person has behandlerdialog-oppgave

- src/data/personregisterHooks.ts
Dobbel negation på en tom liste (`!![]`) gir `true` i javascript, så her gjorde vi et kall med tom liste til backenden unødvendig.
> Fix enabled-field in /info query

- mock/data/personInfoMock.ts
- mock/data/personoversiktEnhetMock.ts
- src/components/filters/BirthDateFilter.tsx
- test/data/fellesTestdata.ts
Vi utvider lista fra 31 til 71 datoer, ettersom at NAV Oppfølging Utland ønsker å filtrere på d-nr i oversikten også. D-nr er som et vanlig fnr, men de to første sifferene har +40 i verdi.
> [IS-1577] Allow veileder to filter on dnr-dates as well

- .github/pull_request_template.md
- mock/data/personoversiktEnhetMock.ts
- mock/mockUtils.ts
- server/unleash.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/components/HendelseTypeFilter.tsx
- src/context/filters/filterContextState.ts
- src/data/personoversiktHooks.ts
- src/data/unleash/types/unleash_types.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/lenkeUtil.tsx
- src/utils/toPersondata.ts
- test/components/Personrad.test.tsx
- test/components/Sokeresultat.test.tsx
- test/data/fellesTestdata.ts
- test/utils/hendelseFilteringUtilsTest.ts
Legger til en ny hendelse i oversikten, som ligger bak featuretoggle for forhåndsvarselet. På den måten vil veiledere som har tilgang til å sende forhåndsvarsel, også få opp den nye hendelsen blant filterene i oversikten. Hvis veileder klikker på personer som har vurder-stans-oppgaven aktivt, vil de bli sendt til `/aktivitetskrav`-siden i syfomodiaperson.
Per nå tror jeg de personene også vil ligge under aktivitetskrav-filteret, ettersom de har et aktivt aktivitetskrav 🤔 Så mulig det er noen forbedringer her på sikt!
> IS-1639: Add new filter for vurder stans

- src/api/types/personoversiktTypes.ts
- src/components/error/ErrorBoundary.tsx
- src/data/personoversiktHooks.ts
- test/query/personoversiktHooks.test.tsx
Prøver å forbedre logikken for å sjekke isUbehandlet i frontend så man slipper å huske å utvide if-en ved nytt filter/oppgave (forhåpentligvis kan vi kvitte oss med dette i frontend og bare sjekke i backend på sikt).
> Improve checking ubehandlet

- src/utils/dateUtils.ts
- test/utils/dateUtils.test.ts
Dette ble fortsatt feil i oversikten ifølge innmelder av jira-saken. Mistenker at Localdate fra APIet ikke blir gjort om til en Date-type i serialiseringen i DTOet, og derfor slenger vi på new Date() rundt alt her slik at sammenligning av datoer blir riktig.
> IS-1766: Make sure all dates are Date

- mock/data/personoversiktEnhetMock.ts
- src/components/Labels.tsx
- src/data/personregisterHooks.ts
- test/components/Personrad.test.tsx
Gjør alltid kall til syfoperson for å hente skjermingskode for personer. Endret samtidig visning av skjermingskode fra tag til ikon med tooltip for å spare plass.
> IS-1760: Always fetch skjermingskode from syfoperson and use icon with tooltip

- src/data/personregisterHooks.ts
- test/query/personregisterHooks.test.tsx
Midlertidig disabler kall til syfoperson som går tregt for noen kontorer. Konsekvens blir at ikon for skjermingskode ikke blir vist i oversikten. Vi må finne en bedre løsning for å hente dette.
> Disable syfoperson call

- mock/data/personInfoMock.ts
- src/api/types/personregisterTypes.ts
- src/containers/OversiktContainer.tsx
- src/data/personregisterHooks.ts
- src/utils/toPersondata.ts
- test/query/personregisterHooks.test.tsx
Enabler henting av skjermingskode fra syfoperson. Dropper å vise vise spinner mens syfoperson-kallet laster. Fjerner navn fra responsen siden vi får dette fra syfooversiktsrv.
Må merges etter https://github.com/navikt/syfoperson/pull/162
> IS-1907: Enable fetching skjermingskode from syfoperson

- src/api/types/personregisterTypes.ts
- src/components/FristColumn.tsx
- src/components/Sorteringsrad.tsx
- src/utils/dateUtils.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/personDataUtil.ts
- src/utils/toPersondata.ts
- test/components/FristColumnTest.tsx
- test/components/Personrad.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
Har i tillegg endret slik at vi viser personen i §8-5-filteret dersom fom-dato finnes (i stedet for sjekk på at den er i fremtiden), som vi har snakket om. Tanken er da at datoen skal nullstilles i oversikten når vedtaket ferdigbehandles (personen vil da forsvinne fra §8-5-filteret).
> IS-2360: Vis friskmelding til arbeidsformidling vedtak-fom i frist-kolonnen og inkluder i filtrering og sortering

- src/components/flexjar/Flexjar.tsx
Vi ønsker å måle om noen klikker på radioknappen, men ikke fullfører skjemaet. Dette kan vi gjøre ved å telle hvor mange som velger en radioknapp når verdien står på `null` (ikke valgt noe fra før), og sammenligne dette med hvor mange som fullfører og trykker `Send`.
Legger også til en slags _reset_ av skjemaet når man lukker knappen, ettersom at komponentene da ikke viste noe, men staten var fortsatt oppdatert. 
Eksempel: Klikker på `Ja`, lukker skjemaet, åpner skjemaet, ingen radioknapp er valgt - men staten er fortsatt `Ja`.
Det samme ble et problem for comboboxen; man kunne ha valgt ett element, lukket skjemaet, åpnet igjen og valgt et annet element. Da holder staten på begge elementene, så begge ville blitt sendt inn.
> IS-2379: Add amplitude measurement for dropoff

- server/config.ts
- server/proxy.ts
Vi får 404 mot flexjar-backend fordi vi sender med `/flexjar-backend` før resten av pathen, og det skal vi helst fjerne før vi proxyer. Bruker derfor en config som ligner mer på den vi har i `syfomodiaperson`.
> IS-2379: Change proxy config so we can remove path-prefix

- src/components/flexjar/Flexjar.tsx
- src/containers/OversiktContainer.tsx
- test/components/flexjar/FlexjarTest.tsx
Egentlig 3 små endringer i én:
- Resultatene i comboboxen var lenger enn selve flexjar-panelet, så for å se nederste alternativ måtte man scrolle heeelt nederst i oversikten. Nå custom-styler vi lengden på denne, til å være ca 190px i stedet for 280px.
- Legger også til en liten endring på formatet vi sender til flexjar. Prøvde å sende `\n` før, men flexjar fjerner uansett denne i admin-panelet.
- Flexjar ble lastet inn før lista ble lastet inn, og siden lista bare er en spinner mens den laster, så hoppet flexjar-panelet opp midt på siden. Litt leit hvis det tar 10 sekunder å laste inn oversikten
<details>
<summary>Screenshot combobox</summary>
Før:
Etter:
</details>
<details>
<summary>Screenshot innlasting</summary>
Før:
Etter:
https://github.com/navikt/syfooversikt/assets/37441744/b4edaf …
> IS-2379: Style combobox-list so results dont go outside screen.

- src/components/VeilederColumn.tsx
- src/components/toolbar/AssignVeileder/TildelVeileder.tsx
- src/components/toolbar/OpenDropdownButton/OpenDropdownButton.tsx
- src/components/toolbar/SearchVeileder/SearchVeileder.tsx
- src/components/toolbar/Toolbar.tsx
- src/utils/assignVeilederUtils.tsx
Først Refactor-commit ble uteglemt i forrige PR. Har i tillegg gjort `TildelVeileder` mindre avhengig av `ToolbarWrapperProps` ved å ikke importere props derfra. Gjør det enklere å ta i bruk `TildelVeileder` fra ny Aksel-tabell-komponent.
> IS-2440: Refactor VeilederColumn and TildelVeileder

- mock/data/personoversiktEnhetMock.ts
- src/api/types/personregisterTypes.ts
- src/components/Labels.tsx
- src/components/LinkSyfomodiaperson.tsx
- src/components/NewOversiktTable.tsx
- src/utils/personDataUtil.ts
- src/utils/stringUtil.ts
- test/components/NewOversiktTableTest.tsx
- test/utils/lenkeUtil.test.ts
- test/utils/personDataUtil.test.ts
Det er jo en litt rar funksjonalitet det her med å defaulte til at fnr er link hvis man mangler navn. Tror egentlig det bare oppstår i dev at vi mangler navn 🤔
- Flytter varseltrekant fra egen kolonne til navnet (eller fnr)
- Lager egen komponent for lenka ut + varsel-labelen
- Ryddet litt i utils-kode
> IS-2457: Move warning-icon from own column to name or personident column

- mock/data/personoversiktEnhetMock.ts
- src/api/types/personoversiktTypes.ts
- src/api/types/personregisterTypes.ts
- src/components/HendelseTypeFilter.tsx
- src/context/filters/filterContextState.ts
- src/data/personoversiktHooks.ts
- src/data/unleash/types/unleash_types.ts
- src/utils/hendelseFilteringUtils.tsx
- src/utils/toPersondata.ts
- test/components/FristColumnTest.tsx
- test/components/NewOversiktTableTest.tsx
- test/components/Sokeresultat.test.tsx
- test/query/personoversiktHooks.test.tsx
- test/utils/hendelseFilteringUtilsTest.ts
- Legger til at vi viser oppfolging i sen fase kandidater i oversikten.
- Se [tilhørende PR](https://github.com/navikt/syfooversiktsrv/pull/389) i `syfooversiktsrv`
> IS-2492: Show sen oppfolging kandidat in oversikt

- mock/data/personoversiktEnhetMock.ts
- src/api/types/personoversiktTypes.ts
- src/components/NewOversiktTable.tsx
- src/utils/statusColumnUtils.ts
- test/components/NewOversiktTableTest.tsx
Flere ting som ikke var helt gjennomtestet her, så prøver å fikse opp litt:
- Manglet `NY_VURDERING` på aktivitetskrav, den må vi også vise i tabellen
- Litt marginer mellom hver hendelse slik at man kan skille de fra hverandre når det er flere
- Aktivitetskrav ligger både under `aktivitetskrav` og `aktivitetskravvurdering` i DTOen, så må ta høyde for begge
- Litt trøbbel med datoer på frister: Må wrappe i `new Date()` for å være sikker på at datoene kan brukes med `<` etc.
- Fikset testene vi kommenterte ut
- Fjerner Veileder-kolonnen når man står på "Min oversikt" for å gi mer plass
> IS-2475: Fix hendelse column

- src/api/types/veilederArbeidstakerTypes.ts
- src/components/Sokeresultat.tsx
- src/data/veiledereQueryHooks.ts
Denne ble ikke brukt til noe i APIet og er fjernet fra backend
> IS-2601: Remove unused enhet prop from dto

- src/components/FristColumn.tsx
- src/utils/hendelseFilteringUtils.tsx
- src/utils/personDataUtil.ts
- test/components/FristColumnTest.tsx
Viser eventuell manglende medvirkning forhåndsvarsel svarfrist i fristkolonnen. Fristen var heller ikke tatt med i logikken for filtrering og sortering på frist.
:thought_balloon:  Vi burde nok gjort noe refaktorering av dette frist-opplegget slik at det blir "vanskeligere" å glemme neste gang vi legger til en frist.
> IS-2696: Add missing manglende medvirkning frist

- src/decorator/decoratorConfig.ts
Når den er satt til `writeOnly` så gjør ikke `fetchActiveEnhetOnMount`
noe, og når ikke enhet er kontrollert fra appen si side så blir aktiv
enhet resatt hver gang siden lastes.
> Fjern enhetSyncMode

- src/api/types/personoversiktTypes.ts
- src/components/FristDataCell.tsx
- src/components/HendelseFilterPanel.tsx
- src/components/NewOversiktTable.tsx
- src/components/OppfolgingsoppgaveModal.tsx
- src/components/Sokeresultat.tsx
- src/components/toolbar/AssignVeileder/TildelVeileder.tsx
- src/components/toolbar/Toolbar.tsx
- src/containers/Oversikt.tsx
- src/context/tab/TabTypeContext.tsx
- test/components/FristColumnTest.tsx
- test/components/HendelseTypeFilter.test.tsx
- Erstatter ikonet for oppfølgingsoppgave med et klikkbart ikon.
- Dette klikkbare ikonet åpner en modal som viser innholdet i oppfølgingsoppgaven
- Ikonet er bare klikkbart når veileder er i "Min oversikt"
https://github.com/user-attachments/assets/91843326-ed6b-4eff-9c79-f84047816cfa
> IS-2649: Show content of oppfolgingsoppgave in oversikt

- src/components/FristDataCell.tsx
- src/mocks/data/personoversiktEnhetMock.ts
Endre tooltipen til oppfølgingsoppgave slik at den følger samme mønster som de andre tooltipene tilhørende andre hendelser. 
Før:
Nå:
> IS-2791: Edit tooltip oppfølgingsoppgave

- src/sider/oversikt/filter/HendelseFilter.tsx
- src/sider/oversikt/sokeresultat/Sokeresultat.tsx
- src/utils/hendelseFilteringUtils.tsx
- test/utils/hendelseFilteringUtilsTest.ts
- Fikser hendelsefilter.
Før - Var flere bokser sjekket av måtte den personen ha alle disse hendelsene for å vises.
Nå - Er flere bokser sjekket av så vises alle personer som har disse hendelsene
https://github.com/user-attachments/assets/f3d5717d-6534-411b-8e19-92ca2472ceb8
> IS-2734: Corrects behaviour of hendelse filter

- src/mocks/data/personoversiktEnhetMock.ts
- src/sider/oversikt/sokeresultat/oversikttable/fristdatacell/OppfolgingsoppgaveModal.tsx
Tekst som inneholder linjeskift vil nå brekke riktig i popup ifm. visning av oppfølgingsoppgaven fra oversikten.
Relatert til: https://github.com/navikt/syfomodiaperson/pull/1602.
>  IS-2995: Endret slik at visning av oppfølgingsoppgaveteksten tar hensyn til whitespace

- src/sider/oversikt/filter/HendelseFilter.tsx
- Fikset slik at "nullstill valg" knappen nullstiller alle feltene i venstre filterboks. Problemet var at hendelsesfilteret nullstilte checkbox første gang man prøvde, men ikke flere ganger etter det. Men de andre boksene funket som de skulle. 
Før: 
https://github.com/user-attachments/assets/27e863d0-9c8d-44df-b015-4596676b2e2d
Nå:
https://github.com/user-attachments/assets/84608e4b-c171-4c45-b363-5ed1566f1f1f
> IS-3030: Fix nullstill valg button

- src/api/types/personoversiktTypes.ts
- src/sider/oversikt/sokeresultat/oversikttable/fristdatacell/OppfolgingsoppgaveModal.tsx
- src/utils/hendelseColumnUtils.ts
Legger til manglende tekst(er) for oppfolgingsgrunn `SAMTALE_MED_BRUKER`.
Legger tekst-variantene (én for modalen og én for hendelse-kolonnen) sammen med enumen og gjør slik at koden ikke kompilerer om man legger inn ny grunn uten å angi tekster.
> IS-3036: Add missing oppfolgingsgrunn text

- src/sider/oversikt/Oversikt.tsx
- src/sider/oversikt/filter/ClearFiltersButton.tsx
- Flyttet nullstill valg knapp der den hører hjemme, inni selve filterboksen. Plassert nederst pga ui mønster. Dette gjør også at filtrene dyttes opp i synsfeltet og blir lettere tilgjengelig. 
- Måler bruk av nullstill knappen
> IS-2838: move and log nullstill valg button

- src/sider/sokperson/SokPerson.tsx
- test/components/SokPersonTest.tsx
- Omformulere tekster for å tydeliggjøre søket. 
- Endret label for å tydeliggjøre hva som er obligatorisk og hva som er valgfritt.
- Lagt til hjelpetekst for å utdype hvordan søket fungerer. Forhåpentligvis er label og description nok for å skjønne hva som kreves i de ulike feltene, men nye brukere kan kanskje trenge en mer utdypning.
- Flyttet errormeldingene under gjeldene input for å følge designmønsteret vi har på andre form i systemet. Hindrer også forvirring om hvilket felt som ikke er gyldig fylt inn. 
- Flyttet på rekkefølgen på initialer og fødselsdato feltet slik at det obligatoriske feltet kommer først. 
Før:
Nå:
https://github.com/user-attachments/assets/79ac4930-c97c-4037-ab18-00b3de441009
> IS-3017: Tydeliggjøre søket

- src/sider/sokperson/SokPerson.tsx
- Lagt til amplitude telling på hvor mange som klipper på hjelpetekst.
> IS-3017: Log helptext click

- src/sider/sokperson/SokPerson.tsx
- src/utils/amplitude.ts
- Lagt til amplitude måling på valideringsfeilene på søk etter sykmeldt.
> IS-3017: Log error message søk

- src/api/types/aktivitetskravDTO.ts
- src/api/types/personoversiktTypes.ts
- src/mocks/data/personoversiktEnhetMock.ts
- src/utils/hendelseColumnUtils.ts
- test/components/FristColumnTest.tsx
- test/components/NewOversiktTableTest.tsx
- test/utils/hendelseFilteringUtilsTest.ts
Lagt til årsaker i parentes hvis aktivitetskravstatus er `AVVENT`. Det er lagt inn synkende sortering på årsaker ettersom jeg tenker det ser penest ut hvis årsaken `ANNET` kommer sist, både visuelt og at det er årsaken som er minst relevant.
> IS-3068: Lagt til visning av årsaker hvis status for aktivitetskravvurdering er AVVENT

- src/mocks/data/personoversiktEnhetMock.ts
- src/sider/oversikt/sokeresultat/oversikttable/PersonRadVirksomhetColumn.tsx
- src/sider/sokperson/SokPersonResultat.tsx
- test/components/SokPersonTest.tsx
Gjenbruker virksomhetskolonnen fra min/enhetens oversikt i søkeresultat-tabellen.
Kan merges etter https://github.com/navikt/syfooversiktsrv/pull/520 (henter ut virksomhetsnummer fra oppfølgingstilfellet til personene i søkeresultatet)
> IS-2892: Lagt til virksomhet-kolonne i søkeresultat

- src/components/EksternLenke.tsx
- src/components/Systemvarsel.tsx
- src/sider/oversikt/OversiktContainer.tsx
Lagt til boks med informasjon om at forhåndsvarsler ikke har gått ut til bruker (gjelder både `Min oversikt` og `Enhetens oversikt`)
Må vente på følgende før merge:
> IS-3179: Lagt til informasjon om forhåndsvarsler som ikke har blitt sendt ut

- src/components/Systemvarsel.tsx
- src/hooks/useLocalStorageState.ts
Legger på en lukkenkapp, og trigger en lagring av tidsstempel i localstorage. Hvis det er mer enn 1 døgn siden denne, viser man alert.
https://github.com/user-attachments/assets/492d2eb5-c78f-469a-84b2-c26b6069cb36
> IS-3190: Hide alert and store in localstorage

- src/sider/oversikt/sokeresultat/toolbar/TildelOppfolgingsenhet/TildelOppfolgingsenhetModal.tsx
- src/utils/amplitude.ts
Er ikke nødvendigvis sikker på om det blir helt rett logikk, men jeg har i alle fall tenkt:
- Vi vil måle hvor mange de klarte å flytte av gangen, feks 2 stk. Selve hendelsen teller antall ganger de bruker funksjonaliteten, og `antall` forteller hvor mange de flyttet av gangen. Mulig det er bedre å sende med `maybeAntall` her hvis vi heller vil måle hvor mange de prøvde å flytte, ikke bare hvor mange som var suksessfulle
- Vi vil måle hvor ofte de får en feil fra backenden
- Vi vil måle dersom de har fått til noen, men ikke alle. Dette utfallet fører til to måleinnslag i amplitude nå. Jeg tenker vi vil se på prosentvis hvor mange som feiler helt, feiler litt og ikke feiler, men da burde vi kanskje ikke dobbelt-telle de som feiler litt 🤔
> IS-3239: Add amplitude logging of tildeling av oppfolgingsenhet

- src/sider/oversikt/sokeresultat/Sokeresultat.tsx
- src/sider/oversikt/sokeresultat/toolbar/TildelOppfolgingsenhet/TildelOppfolgingsenhetButton.tsx
- src/sider/oversikt/sokeresultat/toolbar/TildelOppfolgingsenhet/TildelOppfolgingsenhetModal.tsx
- src/sider/oversikt/sokeresultat/toolbar/Toolbar.tsx
- test/components/TildelOppfolgingsenhetTest.tsx
Fjerner bruk av den globale notification-banneret og flytter feedbacken til den sticky toolbaren. Det gir noen fordeler:
- Alle tilbakemeldinger rundt flyttingen er på samme sted
- Alertene er sticky dersom man scroller nedover lista og brukeren får feedback der man står i lista (må ikke scrolle opp for å se)
- Notificationen blir borte dersom man bytter enhet/side, der den tidligere hang igjen (lite sannsynlig case i prod, men fint å få ryddet opp likevel)
Samtidig så blir ikke Notification brukt noe mer lenger, men den ligger der som en global hook man kan koble seg på når vi trenger det (feks sånn som når vi hadde prodfeil med forhåndsvarslene)
https://github.com/user-attachments/assets/59c20987-9f1c-47ec-bede-b5c622165285
> IS-3252: Move feedback-alerts to sticky part of toolbar

- package-lock.json
- package.json
Solves: https://github.com/navikt/syfooversikt/security/dependabot/98
Dette bumper også `vite` til v6 under the hood. Vi får jo ofte opp en warning når vi kjører testene som går ut på dette: https://v6.vite.dev/guide/troubleshooting.html#cjs
Jeg er ikke såå bevandret i commonjs vs ESM bortsett fra forskjellen i imports, men jeg sparret litt med copilot og det ser ut som vi har en del settings som gjør at vi kan fortsette med en CJS-modul og ha ESM samtidig. Så tror CJS brukes mer på server/webpack-nivået, og så er jo det meste av react-koden i ESM. Kostnaden med å gå over til ESM for hele repoet kan kanskje være litt for stor, men det er ikke sikkert vi trenger det før vi evt går over til Vite for hele appen 🙃
Vi er på `3.0.9` i syfomodiaperson så burde være en safe major-update.
> IS: Bump vitest version

- package-lock.json
- package.json
- server.ts
Kommer fra: https://github.com/navikt/syfooversikt/security/code-scanning/6
Denne krever nok litt testing, både fordi det er mange major-versjoner, og fordi vi endrer på reglene her.
Fra Copilot:
> When updating helmet from 4.6.0 to 8.1.0, there are several breaking changes to be aware of:
**Key Breaking Changes**
> - TypeScript types - Helmet 8.x has improved TypeScript support, so you can remove the as any cast
> - Default CSP - Helmet now enables Content Security Policy by default with stricter settings
> - API changes - Some configuration options have been renamed or restructured
Ser ut som at vi originalt droppet dette fordi det ikke funka med amplitude: https://github.com/navikt/syfomodiaperson/pull/499#issue-788763222
Det skal gå an å evt whiteliste de vi tillater og så kan det …
> IS: Update Helmet and turn on CSP

- src/sider/oversikt/sokeresultat/oversikttable/fristdatacell/FristDataCell.tsx
Endre tilbake til timeglass ikon i stedet for "ark" ikon på klikkbar aktivitetskrav avvent vurdering i oversikten etter tilbakemeldinger etter [denne PRen](https://github.com/navikt/syfooversikt/pull/646). Tilbakemeldingen gikk på at de bruker ikonene for å skille hva som er aktivitetskrav og hva som er oppfølgingsoppgave. 
Nå:
Før:
> IS-3402: Endre ikon på forhåndsvisning av aktivitetskrav i oversikten
